### PR TITLE
Run tests from command line

### PR DESCRIPTION
**Pull request by korniltsev**
Move tests to src/test/java from src/test. Copypaste test dependencies from pom.xml to build.gradle
Can now run tests with `mvn test`, `gradle test`

### CODE REVIEW

**Comment by korniltsev** [comment]
I'l take a look at travis to see why it failed.

Btw do you know travis does nothing right now? Taken from https://travis-ci.org/RuedigerMoeller/fast-serialization/jobs/163650294
```
:test UP-TO-DATE
:check UP-TO-DATE
BUILD SUCCESSFUL

Total time: 6.771 secs
```
Runing all tests required ~5 minute. And travis runs no tests at all in 6 seconds.

**Comment by korniltsev** [comment]
There are two problems:

- Some of the tests are very resource expensive and I belive travis kills test process.
- TestObjectServer is red on travis, but green on my machine.

If I junit.Ignore this tests, the build will be green https://github.com/korniltsev/fast-serialization/pull/2

**Comment by korniltsev** [comment]
So the problem with `StringOffHeapTest#hardcore` and other was memory related and fixed by increasing heap for test.
The only one red test is TestObjectServer with "Connection refused" exception in one of three setups(jdks).

**Comment by RuedigerMoeller** [comment]
Thanks for your help !

**Comment by RuedigerMoeller** [comment]
thanks for helping. Hm .. what does the "All checks have failed" message above means (note i am not familar with travis, was provided by a contributor)
image

**Comment by korniltsev** [comment]
TestObjectServer is still red when run on travis. It is the only red test I failed to fix.

> java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at java.net.Socket.<init>(Socket.java:425)
    at java.net.Socket.<init>(Socket.java:208)
    at org.nustaq.net.TCPObjectSocket.<init>

You can click details and see the build log on travis.

**Pull request closed without merging**
