### PR TITLE
couple of enhancements in order to reduce memory footprint

### PR DESCRIPTION
**Pull request by carlosraphael**
Simple code changes to reduce memory footprint by adding a simple unbounded object pool strategy to reuse FSTFieldInfo instances. Aside that FSTInt2ObjectMap and FSTIdentity2IdMap are being always cleaned by using the new fastClear method rather than creating new instances when we've got huge mem areas after having written/reading a large object

### CODE REVIEW

**Comment by RuedigerMoeller** [comment]
Hi,
thanks for your work.

* pooling fieldinfo's is already implemented (see FSTClazzInfo.sharedFieldSets). Also classloading issues (when using different classloaders per configuration) and concurrency issues can arise from pooling. 

* regarding fast clear, I first will have to run the benchmark suite as changes in objectstream setup / teardown can have giant impact on small-message throughput (init is more expensive than seerializing the actual object).

**Comment by carlosraphael** [comment]
Hi there,

There seems to be really an object pool for FSTFieldInfo. However, when profiling an application, which makes use of direct off-heap serialization(OffHeapCoder), I could see loads of FSTFieldInfo being always created. Perhaps at the time I was using an old version, but by following the code ->

here: https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTObjectOutput.java#L317

and here: https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTObjectOutput.java#L290

It doesn't seem to be using the object pool you mentioned.

Yet about my BasicObjectPool, it could take a concurrent data structure(e.g. ConcurrentLinkedDeque) to prevent concurrency issues.

Moving onto the fast clear, sorry, but I didn't get what you said. From my point of view it kinda doesn't make sense to loop through arrays to clear them when you can simply dispose them to GC without putting extra pressure on CPU or even on memory once it's gonna create a new instance when size reaches a certain threshold(https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTObjectRegistry.java#L63). I also saw, when profiling with JMC, loads of FSTInt2ObjectMap/FSTIdentity2IdMap being created over and over.

Anyway, thanks a million for your feedback.

**Comment by RuedigerMoeller** [comment]
Hi, 

* I have to investigate regarding fieldinfo cache usage. Even when cached, a lot of fieldinfo instances are created initially. However the cache was introduced in an app with 10k concurrent websocket connections each using a separate fstconfiguration and had a big impact, so i assume its active and working.

* note that a common mistake is to not reuse FSTConfiguration which will result in a lot of object creation.

* fastclear: actual behaviour of JVM/Hardware can be very counterintuitive. 'disposing' arrays to GC is really bad regarding cache locality (lots of cache misses), those changes have been introduced because of extensive benchmarking (https://github.com/RuedigerMoeller/serialization-benchmark). A cache miss can be worth 1000+ cpu ops (depends on cpu and memory hardware). I'd really like benchmark the change before adding the change.

**Comment by RuedigerMoeller** [comment]
* global field cache will clash with classloader trickery

**Comment by RuedigerMoeller** [comment]
upon closer review I think the cache does not introduce any classloading related issues. Will have to check if fastclear actually deserves its name in case of large streams (beyond 100MB) ..
Thanks for your contribution !

**Pull request closed without merging**
