### PR TITLE
Crash during simple migration (field addition)

### PR DESCRIPTION
**Pull request by korniltsev**
I create a simple object
```
public class DTO implements Serializable {
    public String field1 = "fieldInit1";
}
```
Then I add a second field.
```
public class DTO implements Serializable {
    public String field1 = "fieldInit1";
    public String field2 = "fieldInit2";
}
```
And then it crashes
```
java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 29

	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1124)
	at migration.MigrationTest.migrationAddFields(MigrationTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 29
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:290)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFShort(FSTStreamDecoder.java:360)
	at org.nustaq.serialization.FSTClazzNameRegistry.decodeClass(FSTClazzNameRegistry.java:163)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readClass(FSTStreamDecoder.java:472)
	at org.nustaq.serialization.FSTObjectInput.readClass(FSTObjectInput.java:933)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:343)
	at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708)
	at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
	... 30 more
```
Is migration (field addition/removal ) supported?

### CODE REVIEW

**Comment by RuedigerMoeller** [comment]
Migration is not supported (see wiki) because of severe runtime cost. You need to add versioning support manually on top of fst.

**Comment by korniltsev** [comment]
I've found duplicate issue https://github.com/RuedigerMoeller/fast-serialization/issues/155 I believe it should be closed too

**Comment by korniltsev** [comment]
Looks like I cand add fields if I annotate them with `org.nustaq.serialization.annotations.Version`

**Comment by RuedigerMoeller** [comment]
yes, but they should only contain types which are known prior in the object graph (e.g. int,long,etc. basic jdk classes). You really need to understand how object graph serialization works. 

What's also working is to 
* create a new class subclassing the old one
* add an Object extension = null; field to classes which might carry additional data later on
* use JSON configuration (slow, not fully JDK-ser compatible)

**Pull request closed without merging**
