### PR TITLE
Compile against java6

### PR DESCRIPTION
**Pull request by cakofony**
Unsure if this is something that you care about.

### CODE REVIEW

**Comment by RuedigerMoeller** [comment]
ok, we definitely start cobolizing in the java community ;). Its probably safest to create a dedicated java6 branch .. thanks for your contribution

**Comment by cakofony** [comment]
Would be wonderful to get java 6 compatible jars published to maven! I'm happy to help if there's anything you'd like from my end.
Thanks for the quick reply!

**Comment by RuedigerMoeller** [comment]
i merged this into a new branch also backported the tests (on fails: i70.java). I haven't run tests against a real jdk 1.6 (there might be missing methods used).
it's available on maven as 2.48-jdk1.6 or so (within some hours)

**Comment by cakofony** [comment]
Wonderful, I can't thank you enough!

**Pull request closed without merging**
