### PR TITLE
Added Travis CI configuration

### PR DESCRIPTION
**Pull request by mafagafogigante**
Just toggle this repository on in your Travis CI account before merging this PR, OK?

This way there will be 3 builds using the JDKs you can read in the file and they all use `gradle assemble` followed by `gradle check`. If there is a problem with this, leave a comment.

### CODE REVIEW

**Comment by RuedigerMoeller** [comment]
thanks a lot :+1: not sure what happens by doing this, anyways

**Comment by RuedigerMoeller** [comment]
got my first travis mail :+1:

**Comment by mafagafogigante** [comment]
If you need me to disable those, just ask. But that will automatically test incoming PRs for you so you don't have to do it locally.

**Comment by mafagafogigante** [comment]
Note that Maven is not tested. So even if someone breaks the pom.xml file, the tests will pass because just Gradle is used.

**Comment by RuedigerMoeller** [comment]
ah .. ok.

2015-11-20 16:48 GMT+01:00 Bernardo Sulzbach <notifications@github.com>:

**Comment by mafagafogigante** [comment]
You can, obviously, make an issue from this and wait for someone to "fix" it. As it is **much** more likely that someone will break the application than the maven configuration, it is not a big deal.

**Comment by RuedigerMoeller** [comment]
yeah, i thinks its ok as is. enjoying 'build passing' mails from travis :). Do you know how i can put the little 'build passing' icon into the readme.md ?

**Comment by mafagafogigante** [comment]
Yes, I do. I don't know if you are sarcastic or not about these emails, but I like getting broken/fixed messages

If a break a branch I will get a Broken message. After fixing it, a Fixed message. That helps me prevent broken builds into the master branch.

broken_fixed

**Comment by RuedigerMoeller** [comment]
No, I am not sarcastic. I am happy with this improvement, actually I accidentally broke the build in the past several times.

**Pull request merged**
